### ISSUE TITLE
Error while loading file

### ISSUE THREAD

**Issue by stephenstrenn** [philipstarkey/bitbucket-hg-exporter#38]
Been using your excellent tool to transfer some repos to github.  Thank you very much for you efforts.  On my final (and most important :) repo the error shown below popped up **after** 275 issues had imported without a problem.  Any ideas on how to fix this or what might be wrong?  I've attached the offending file mentioned at the end of the error (NOTE: I changed file extension to TXT so that github would allow it to be uploaded)

[issues_page=3.txt](https://github.com/philipstarkey/bitbucket-hg-exporter/files/4362509/issues_page.3.txt)

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\bitbucket-hg-exporter.exe\__main__.py", line 9, in <module>
  File "c:\program files\python38\lib\site-packages\bitbucket_hg_exporter\__main__.py", line 2388, in main
    project = MigrationProject()
  File "c:\program files\python38\lib\site-packages\bitbucket_hg_exporter\__main__.py", line 273, in __init__
    self.__start_project()
  File "c:\program files\python38\lib\site-packages\bitbucket_hg_exporter\__main__.py", line 327, in __start_project
    self.__confirm_project_settings()
  File "c:\program files\python38\lib\site-packages\bitbucket_hg_exporter\__main__.py", line 1180, in __confirm_project_settings
    import_issues_to_github(bb_repo, gh_repo, github_auth, copy.deepcopy(self.__settings), mapping, dry_run=False)
  File "c:\program files\python38\lib\site-packages\bitbucket_hg_exporter\issue_migrate.py", line 121, in import_issues_to_github
    resp = verify_github_issue_import_finished(
  File "c:\program files\python38\lib\site-packages\bitbucket_hg_exporter\issue_migrate.py", line 469, in verify_github_issue_import_finished
    raise RuntimeError(
RuntimeError: Failed to import GitHub issue due to the following errors:
{'id': 2815790, 'status': 'failed', 'url': 'https://api.github.com/repos/affinitybio/lifescale-m3/import/issues/2815790', 'import_issues_url': 'https://api.github.com/repos/affinitybio/lifescale-m3/import/issues', 'repository_url': 'https://api.github.com/repos/affinitybio/lifescale-m3', 'created_at': '2020-03-20T20:32:56.000-07:00', 'updated_at': '2020-03-20T20:32:56.000-07:00', 'errors': [{'location': 'n/a', 'resource': 'Internal Error', 'field': None, 'value': '15eb18b3d8c5485c4cb1bd23ab86ff272468acd1', 'code': 'error'}]}
Error while loading file C:\Users\sstrenn\Documents\ls\gh-pages\data/repositories/affinitybio/lifescale-m3/issues_page=3.json

**Comment by philipstarkey** [comment]
Glad you're finding it useful!

The error you are seeing is actually a bit misleading due to the way I catch errors. I should probably fix it but it's low down on my priority list (since it's just the last message that is misleading).

Looking up the stack trace the error actually came while trying to query the GitHub API. I've seen this once before on one of my repositories and it seemed to just be a glitch on the GitHub end. As far as I could tell, the issue it crashed on for me was completely imported correctly. You should check your repository to confirm the last issue is all there, and if so you can just relaunch the tool to pick up where it left off (it will need to reload some data from disk and will warn you about resuming the issue import but it should work fine!)

**Comment by stephenstrenn** [comment]
OK, it's up and running again per your instructions.  If I don't report
back, it means it worked and everyone at my lab will be happy!  Thanks
again for your efforts.

Cheers,
Stephen

**Comment by philipstarkey** [comment]
Closing as no update means it was a transient GitHub issue.
